site:
  title: GDCubism
  url: http://localhost/
  start_page: gd_cubism::ja/index.adoc
content:
  sources:
    - url: https://github.com/MizunagiKB/gd_cubism.git
      branches: 0.6-antora
      start_path: docs
ui:
  bundle:
    url: https://github.com/asciidoctor/asciidoctor-docs-ui/releases/download/prod-284/ui-bundle.zip
output:
  dir: ./public
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [ja, en]
